openapi: 3.0.3
info:
  title: Todo List API
  description: A simple Todo List API for demonstration purposes
  version: 1.0.0

servers:
  - url: https://api.todos.example.com/v1
    description: Production server

paths:
  /todos:
    get:
      operationId: listTodos
      summary: List all todos
      parameters:
        - name: completed
          in: query
          schema:
            type: boolean
          description: Filter by completion status
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

    post:
      operationId: createTodo
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Todo created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /todos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

    get:
      operationId: getTodo
      summary: Get a todo by ID
      responses:
        '200':
          description: Todo details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found

    patch:
      operationId: updateTodo
      summary: Update a todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
      responses:
        '200':
          description: Todo updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

    delete:
      operationId: deleteTodo
      summary: Delete a todo
      responses:
        '204':
          description: Todo deleted

components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - completed
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        dueDate:
          type: string
          format: date
        priority:
          type: string
          enum: [low, medium, high]
        createdAt:
          type: string
          format: date-time

    CreateTodoRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        priority:
          type: string
          enum: [low, medium, high]
          default: medium

    UpdateTodoRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        dueDate:
          type: string
          format: date
        priority:
          type: string
          enum: [low, medium, high]
