// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 LEHRO Solutions
import * as fs from 'fs';
import * as path from 'path';
import { telemetry } from '../../core/telemetry.js';
import { createSpinner } from '../utils/spinner.js';
import { mergeWithConfig } from '../utils/config.js';
import { ui } from '../utils/ui.js';

interface InitOptions {
  template?: string;
  output?: string;
}

const VALID_TEMPLATES = ['openapi', 'graphql'];

export async function initCommand(options: InitOptions) {
  const mergedOptions = mergeWithConfig(options, 'init');
  const { template = 'openapi', output = '.' } = mergedOptions;
  const targetDir = path.resolve(output);

  if (!VALID_TEMPLATES.includes(template.toLowerCase())) {
    ui.error('Unknown template', `Choose one of: ${VALID_TEMPLATES.join(', ')}`);
    process.exit(1);
  }

  ui.showCompactBanner();
  ui.sectionHeader('Project Initialization');

  telemetry.track('init_start', { template });

  if (fs.existsSync(targetDir) && fs.readdirSync(targetDir).length > 0) {
    ui.error('Output directory is not empty', ui.filePath(targetDir));
    ui.info('Resolution', 'Choose an empty directory or create a new one.');
    telemetry.track('init_fail', { reason: 'directory_not_empty' });
    process.exit(1);
  }

  const spinner = await createSpinner(`Creating ${template} project...`);
  if (spinner.start) spinner.start();

  try {
    fs.mkdirSync(targetDir, { recursive: true });
    fs.mkdirSync(path.join(targetDir, 'specs'));
    fs.mkdirSync(path.join(targetDir, 'generated'));
    fs.mkdirSync(path.join(targetDir, 'tests'));

    const packageJson = {
      name: path.basename(targetDir),
      version: '1.0.0',
      description: `Generated ${template.toUpperCase()} API project`,
      scripts: {
        generate: 'gidevo-api-tool generate -s specs/api.yaml -o generated',
        validate: 'gidevo-api-tool validate specs/api.yaml',
        'validate:strict': 'gidevo-api-tool validate specs/api.yaml --strict',
      },
    };

    fs.writeFileSync(path.join(targetDir, 'package.json'), JSON.stringify(packageJson, null, 2));

    if (template === 'openapi') {
      const spec = {
        openapi: '3.0.0',
        info: {
          title: 'Core API',
          version: '1.0.0',
          description: 'Generated by GIDEVO API Tool',
        },
        servers: [{ url: 'http://localhost:3000', description: 'Development server' }],
        paths: {
          '/health': {
            get: {
              summary: 'Health check',
              operationId: 'getHealth',
              tags: ['System'],
              responses: {
                '200': {
                  description: 'System is healthy',
                  content: {
                    'application/json': {
                      schema: {
                        type: 'object',
                        properties: {
                          status: { type: 'string', example: 'healthy' },
                          timestamp: { type: 'string', format: 'date-time' },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      };
      fs.writeFileSync(path.join(targetDir, 'specs', 'api.yaml'), JSON.stringify(spec, null, 2));
    } else if (template === 'graphql') {
      const schema = `# Generated by GIDEVO API Tool
# GraphQL schema template

type Query {
  ping: Pong!
  systemStatus: SystemHealth!
}

type Pong {
  message: String!
  latency: Int!
}

type SystemHealth {
  status: String!
  uptime: Float!
  version: String!
}

schema {
  query: Query
}
`.trim();
      fs.writeFileSync(path.join(targetDir, 'specs', 'schema.graphql'), schema);
    }

    const readme = `# ${path.basename(targetDir)}

> Generated with **GIDEVO API Tool**.

## Quick Start

\`\`\`bash
# Generate SDK
npm run generate

# Validate spec
npm run validate
\`\`\`

## Project Structure

\`\`\`
${path.basename(targetDir)}/
|-- specs/          # API specs (OpenAPI/GraphQL)
|-- generated/      # Generated SDK files
|-- tests/          # Project tests
|-- package.json    # Project scripts
\`\`\`
`.trim();
    fs.writeFileSync(path.join(targetDir, 'README.md'), readme);

    if (spinner.stop) spinner.stop();

    ui.success('Project created');

    ui.table(
      ['Path', 'Purpose'],
      [
        [ui.filePath('specs/'), 'API specifications'],
        [ui.filePath('generated/'), 'Generated SDK output'],
        [ui.filePath('tests/'), 'Project tests'],
        [ui.filePath('package.json'), 'Project scripts'],
      ]
    );

    ui.nextSteps([
      `cd ${path.basename(targetDir)}`,
      'Define your schema in specs/',
      'Generate an SDK: npm run generate',
    ]);

    telemetry.track('init_success', { template });
  } catch (error: any) {
    if (spinner.stop) spinner.stop();
    ui.error('Project initialization failed', error.message);
    telemetry.captureException(error);
    process.exit(1);
  }
}
